### PR TITLE
Add Microsoft Edge Support

### PR DESCRIPTION
**Pull request by earthpyy**
## Changes
- Added Microsoft Edge support (keyword: `edge`)
- Update README about Microsoft Edge
- Fix typo `<browser>-profile` to `<browser>-profiles` in **Commands** section

### CODE REVIEW

**Comment by earthpyy** [comment]
Related with #71

**Comment by mdreizin** [comment]
@earthpyy Could you please enable GitHub Actions on your fork?

**Comment by mdreizin** [comment]
@earthpyy I was wrong, just merged a fix to have working GitHub workflow.

**Comment by mdreizin** [comment]
@earthpyy Could you please disable GitHub Actions on your fork?

**Pull request merged**
